CREATE OR REPLACE PROCEDURE PRC_ANT_PATO_FAMILIARES (
  V_CD_FORMULARIO CHAR,
  V_CD_ATENDIMIENTO NUMBER,
  V_FECHA_REGISTRO DATE,
  V_USUARIO CHAR,
  V_CD_DOCUMENTO_CLINICO NUMBER,
  V_TIPO_PARTO NVARCHAR2,
  V_CONDICION_PARTO NVARCHAR2,
  V_EDAD_ACTUAL NVARCHAR2,
  V_OBSERVACIONES NVARCHAR2,
  V_CD_REGISTRO_SECUENCIAL NUMBER
) IS V_SEC NUMBER;

BEGIN
-- verifica si es insercion o actualizacion
IF V_CD_REGISTRO_SECUENCIAL IS NULL THEN
-- calcula el siguiente secuencial
BEGIN
SELECT
  NVL(MAX(CD_REGISTRO_SECUENCIAL), 0) + 1 INTO V_SEC
FROM
  T_ANTECEDENTES_PATO_FAMILIARES
WHERE
  CD_ATENDIMENTO = V_CD_ATENDIMIENTO;

EXCEPTION WHEN OTHERS THEN V_SEC := 1;

END;

BEGIN
INSERT INTO
  T_ANTECEDENTES_PATO_FAMILIARES (
    CD_FORMULARIO,
    CD_ATENDIMENTO,
    FECHA_REGISTRO,
    USUARIO,
    CD_DOCUMENTO_CLINICO,
    TIPO_PARTO,
    CONDICION_PARTO,
    EDAD_ACTUAL,
    OBSERVACIONES,
    CD_REGISTRO_SECUENCIAL
  )
VALUES
  (
    V_CD_FORMULARIO,
    V_CD_ATENDIMIENTO,
    V_FECHA_REGISTRO,
    V_USUARIO,
    V_CD_DOCUMENTO_CLINICO,
    V_TIPO_PARTO,
    V_CONDICION_PARTO,
    V_EDAD_ACTUAL,
    V_OBSERVACIONES,
    V_SEC
  );

EXCEPTION WHEN OTHERS THEN NULL;

END;

ELSE
BEGIN
UPDATE T_ANTECEDENTES_PATO_FAMILIARES
SET
  CD_FORMULARIO = V_CD_FORMULARIO,
  FECHA_REGISTRO = V_FECHA_REGISTRO,
  USUARIO = V_USUARIO,
  CD_DOCUMENTO_CLINICO = V_CD_DOCUMENTO_CLINICO,
  TIPO_PARTO = V_TIPO_PARTO,
  CONDICION_PARTO = V_CONDICION_PARTO,
  EDAD_ACTUAL = V_EDAD_ACTUAL,
  OBSERVACIONES = V_OBSERVACIONES
WHERE
  CD_REGISTRO_SECUENCIAL = V_CD_REGISTRO_SECUENCIAL
  AND CD_ATENDIMENTO = V_CD_ATENDIMIENTO;

EXCEPTION WHEN OTHERS THEN NULL;

END;

END IF;

COMMIT;

END PRC_ANT_PATO_FAMILIARES;
