SELECT
    ANTECEDENTES.CD_REGISTRO_SECUENCIAL ID,
    ANTECEDENTES.FECHA_REGISTRO         AS "FECHA REGISTRO",
    ANTECEDENTES.USUARIO                USUARIO,
    ANTECEDENTES.TIPO_PARTO             AS "TIPO PARTO",
    ANTECEDENTES.CONDICION_PARTO        AS "CONDICION PARTO",
    ANTECEDENTES.EDAD_ACTUAL            AS "EDAD ACTUAL",
    ANTECEDENTES.OBSERVACIONES          OBSERVACIONES
FROM
    EDITOR_CUSTOM.T_ANTECEDENTES_PATO_FAMILIARES ANTECEDENTES
WHERE
    ANTECEDENTES.CD_ATENDIMENTO = 654