-- Create table
CREATE TABLE T_ANTECEDENTES_PATO_FAMILIARES (
    CD_FORMULARIO CHAR(5),
    CD_ATENDIMENTO NUMBER(10) NOT NULL,
    FECHA_REGISTRO DATE,
    USUARIO NVARCHAR2(100),
    CD_DOCUMENTO_CLINICO NUMBER(10),
    MADRE NVARCHAR2(100),
    PADRE NVARCHAR2(100),
    OTROS_FAMILIARES NVARCHAR2(100),
    ANTECEDENTES_PRENATALES NVARCHAR2(200),
    HORAS_HIDRORREA NVARCHAR2(50),
    NUMERO_TACTOS NVARCHAR2(50),
    LABOR NVARCHAR2(50),
    CANTIDAD NVARCHAR2(50),
    OLOR NVARCHAR2(50),
    CARACTERISTICAS NVARCHAR2(50),
    SUFRIMIENTO NVARCHAR2(50),
    FECHA_NACIMIENTO NVARCHAR2(50),
    HORA_NACIMIENTO NVARCHAR2(50),
    FECHA_ULTIMA_MENSTRUACION NVARCHAR2(50),
    CAPURRO NVARCHAR2(50),
    ECO_EXTRAPOLADO NVARCHAR2(50),
    BALLARD NVARCHAR2(50),
    CD_REGISTRO_SECUENCIAL NUMBER(10) NOT NULL
) TABLESPACE MVEDITOR_CUSTOM_D PCTFREE 10 INITRANS 1 MAXTRANS 255 STORAGE (
    INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED
);

-- Create/Recreate primary, unique and foreign key constraints
ALTER TABLE T_ANTECEDENTES_PATO_FAMILIARES ADD CONSTRAINT PK_ANTECEDENTES_PATO_ PRIMARY KEY (CD_ATENDIMENTO, CD_REGISTRO_SECUENCIAL) USING INDEX TABLESPACE MVEDITOR_CUSTOM_D PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE ( INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED );

-- Grant/Revoke object privileges
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES, ALTER, INDEX, DEBUG, READ ON T_ANTECEDENTES_PATO_FAMILIARES TO ACESSOPRD;

GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES, ALTER, INDEX, DEBUG, READ ON T_ANTECEDENTES_PATO_FAMILIARES TO DBAEDITOR;

GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES, ALTER, INDEX, DEBUG, READ ON T_ANTECEDENTES_PATO_FAMILIARES TO DBAMV;

GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES, ALTER, INDEX, DEBUG, READ ON T_ANTECEDENTES_PATO_FAMILIARES TO EDITOR;

GRANT SELECT, INSERT, UPDATE, DELETE, ALTER, DEBUG, READ ON T_ANTECEDENTES_PATO_FAMILIARES TO MV2000;