CREATE OR REPLACE PROCEDURE PRC_INSERTA_T_ATEN_ACTUAL_NEO (
    V_CD_FORMULARIO CHAR,
    V_CD_ATENDIMIENTO NUMBER,
    V_FECHA_REGISTRO DATE,
    V_USUARIO NVARCHAR2,
    V_CD_DOCUMENTO_CLINICO NUMBER,
    V_REANIMACION CHAR,
    V_ESTIMULACION CHAR,
    V_RADIO_ASPIRACION CHAR,
    V_TUBO_ENDOTRAQUEAL CHAR,
    V_MASAJE_CARD CHAR,
    V_MEDICACION CHAR,
    V_RADIO_VITAMINA_K CHAR,
    V_RADIO_OCULAR CHAR,
    V_REFLEJO_SUCCION NVARCHAR2,
    V_TOLERACIA_ORAL NVARCHAR2,
    V_DEPOSICION NVARCHAR2,
    V_ORINA NVARCHAR2,
    V_TRATAMIENTO_INICIAL NVARCHAR2
) IS
BEGIN
    /* Eliminar datos si existen */
    DELETE FROM T_ATENCION_ACTUAL_NEO
    WHERE CD_ATENDIMENTO = V_CD_ATENDIMIENTO;
    COMMIT;

    /* Insertar nuevos datos */
    INSERT INTO T_ATENCION_ACTUAL_NEO (
        CD_FORMULARIO,
        CD_ATENDIMENTO,
        FECHA_REGISTRO,
        USUARIO,
        CD_DOCUMENTO_CLINICO,
        REANIMACION,
        ESTIMULACION,
        RADIO_ASPIRACION,
        TUBO_ENDOTRAQUEAL,
        MASAJE_CARD,
        MEDICACION,
        RADIO_VITAMINA_K,
        RADIO_OCULAR,
        REFLEJO_SUCCION,
        TOLERANCIA_ORAL,
        DEPOSICION,
        ORINA,
        TRATAMIENTO_INICIAL


    ) VALUES (
        V_CD_FORMULARIO,
        V_CD_ATENDIMIENTO,
        V_FECHA_REGISTRO,
        V_USUARIO,
        V_CD_DOCUMENTO_CLINICO,
        V_REANIMACION,
        V_ESTIMULACION,
        V_RADIO_ASPIRACION,
        V_TUBO_ENDOTRAQUEAL,
        V_MASAJE_CARD,
        V_MEDICACION,
        V_RADIO_VITAMINA_K,
        V_RADIO_OCULAR,
        V_REFLEJO_SUCCION,
        V_TOLERACIA_ORAL,
        V_DEPOSICION,
        V_ORINA,
        V_TRATAMIENTO_INICIAL
    );

    /* Confirmar los cambios */
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        NULL; /* Manejar excepciones */
END PRC_INSERTA_T_ATEN_ACTUAL_NEO;
