CREATE OR REPLACE PROCEDURE PRC_ELIMINA_MEDICAMENTO(
    V_CD_ATENDIMENTO NUMBER,
    V_CD_REGISTRO_SECUENCIAL NUMBER,
    v_numero_formulario number
) IS
BEGIN
    DELETE FROM T_INFORMACION_MEDICAMENTO
    WHERE
        CD_ATENDIMENTO=V_CD_ATENDIMENTO
        AND CD_REGISTRO_SECUENCIAL =V_CD_REGISTRO_SECUENCIAL
        and cd_secuencial = v_numero_formulario;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        NULL;
END PRC_ELIMINA_MEDICAMENTO;