/*  */
SELECT
    *
FROM
    ESP_MED
    INNER JOIN ESPECIALID
    ON ESP_MED.CD_ESPECIALID = ESPECIALID.CD_ESPECIALID
WHERE
    CD_PRESTADOR = 2276
    AND ESP_MED.SN_ESPECIAL_PRINCIPAL = 'S'
 /*  */
    SELECT
        *
    FROM
        ESP_MED
        INNER JOIN ESPECIALID
        ON ESP_MED.CD_ESPECIALID = ESPECIALID.CD_ESPECIALID
    WHERE
        CD_PRESTADOR = 2384
 --and esp_med.sn_especial_principal = 'S'

 /*  */
SELECT
    *
FROM
    PRESTADOR
 /*  */
SELECT
    ESPECIALID.DS_ESPECIALID
FROM
    USUARIOS
    INNER JOIN PRESTADOR
    ON PRESTADOR.CD_PRESTADOR = USUARIOS.CD_PRESTADOR
    INNER JOIN ESP_MED
    ON ESP_MED.CD_PRESTADOR = PRESTADOR.CD_PRESTADOR
    INNER JOIN ESPECIALID
    ON ESP_MED.CD_ESPECIALID = ESPECIALID.CD_ESPECIALID
WHERE
--prestador.cd_prestador = 2276
    USUARIOS.CD_USUARIO = 'PBASANTES'
    AND ESP_MED.SN_ESPECIAL_PRINCIPAL = 'S'
WHERE
    USUARIOS.CD_PRESTADOR = 2276
 /*  */
SELECT
    *
FROM
    ESPECIALID