CREATE OR REPLACE PROCEDURE PRC_ELIMINA_DIAG_INFECCION(
    --V_CD_ATENDIMENTO NUMBER,
    V_CD_PRESCRIPCION NUMBER,
    V_CD_REGISTRO_SECUENCIAL NUMBER
    
) IS
BEGIN
    DELETE FROM T_DIAGNOSTICO_DE_INFECCION
    WHERE
        --CD_ATENDIMENTO=V_CD_ATENDIMENTO
        CD_PRESCRIPCION = V_CD_PRESCRIPCION
        AND CD_REGISTRO_SECUENCIAL =V_CD_REGISTRO_SECUENCIAL;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        NULL;
END PRC_ELIMINA_DIAG_INFECCION;
