CREATE OR REPLACE PROCEDURE PRC_INSERTA_T_AUTORIZA_ANTI (
    V_CD_FORMULARIO CHAR,
    V_CD_ATENDIMIENTO NUMBER,
    V_CD_PRESCRIPCION NUMBER,
    V_FECHA_REGISTRO DATE,
    V_USUARIO NVARCHAR2,
    V_CD_DOCUMENTO_CLINICO NUMBER,
    V_DIAGNOSTICO_DE_INGRESO CLOB,
    V_SERVICIO_SOLICITANTE NVARCHAR2,
    V_MEDICO_TRATANTE_SOLICITANTE NVARCHAR2,
    V_TIPO_INFECCION NVARCHAR2,
    V_MICROORGANISMO_1 NVARCHAR2,
    V_MICROORGANISMO_2 NVARCHAR2,
    V_MICROORGANISMO_3 NVARCHAR2,
    V_MICROORGANISMO_4 NVARCHAR2,
    v_SENSIBILIDAD_1 NVARCHAR2,
    v_SENSIBILIDAD_2 NVARCHAR2,
    v_SENSIBILIDAD_3 NVARCHAR2,
    v_SENSIBILIDAD_4 NVARCHAR2,
    V_ANTIBIOTICO_USADOS_PREV NVARCHAR2,
    V_OTROS_CRITERIOS NVARCHAR2,
    V_ANTIBIOTICO_RADIO NVARCHAR2,
    V_ESTADO NVARCHAR2,
    V_MOTIVO NVARCHAR2,
    V_VALIDADO_POR NVARCHAR2
) IS
BEGIN
    /* Eliminar datos si existen */
    /* DELETE FROM T_AUTORIZACION_ANTIBIOTICOS
    WHERE CD_ATENDIMENTO = V_CD_ATENDIMIENTO;
    COMMIT; */

    /* Insertar nuevos datos */
    INSERT INTO T_AUTORIZACION_ANTIBIOTICOS (
        CD_FORMULARIO,
        CD_ATENDIMENTO,
        CD_PRESCRIPCION,
        FECHA_REGISTRO,
        USUARIO,
        CD_DOCUMENTO_CLINICO,
        DIAGNOSTICO_DE_INGRESO,
        SERVICIO_SOLICITANTE,
        MEDICO_TRATANTE_SOLICITANTE,
        TIPO_INFECCION,
        MICROORGANISMOS_1,
        MICROORGANISMOS_2,
        MICROORGANISMOS_3,
        MICROORGANISMOS_4,
        SENSIBILIDAD_1,
        SENSIBILIDAD_2,
        SENSIBILIDAD_3,
        SENSIBILIDAD_4,
        ANTIBIOTICOS_USADOS_PREV,
        OTROS_CRITERIOS,
        ANTIBIOTICO_RADIO,
        ESTADO,
        MOTIVO,
        VALIDADO_POR
        

    ) VALUES (
        V_CD_FORMULARIO,
        V_CD_ATENDIMIENTO,
        V_CD_PRESCRIPCION,
        V_FECHA_REGISTRO,
        V_USUARIO,
        V_CD_DOCUMENTO_CLINICO,
        V_DIAGNOSTICO_DE_INGRESO,
        V_SERVICIO_SOLICITANTE,
        V_MEDICO_TRATANTE_SOLICITANTE,
        V_TIPO_INFECCION,
        V_MICROORGANISMO_1,
        V_MICROORGANISMO_2,
        V_MICROORGANISMO_3,
        V_MICROORGANISMO_4,
        v_SENSIBILIDAD_1,
        v_SENSIBILIDAD_2,
        v_SENSIBILIDAD_3,
        v_SENSIBILIDAD_4,
        V_ANTIBIOTICO_USADOS_PREV,
        V_OTROS_CRITERIOS,
        V_ANTIBIOTICO_RADIO,
        V_ESTADO,
        V_MOTIVO,
        V_VALIDADO_POR
        
    );

    /* Confirmar los cambios */
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        NULL; /* Manejar excepciones */
END PRC_INSERTA_T_AUTORIZA_ANTI;
