CREATE OR REPLACE PROCEDURE PRC_INSERTA_T_DIAG_INFECCION (
    V_CD_FORMULARIO CHAR,
    V_CD_ATENDIMIENTO NUMBER,
    V_FECHA_REGISTRO DATE,
    V_USUARIO NVARCHAR2,
    V_CD_DOCUMENTO_CLINICO NUMBER,
    V_DIAGNOSTICO_DE_INFECCION NVARCHAR2,
    V_CD_REGISTRO_SECUENCIAL NUMBER,
    V_CD_PRESCRIPCION NUMBER
) IS V_SEC NUMBER;

BEGIN
-- verifica si es insercion o actualizacion
IF V_CD_REGISTRO_SECUENCIAL IS NULL THEN
-- calcula el siguiente secuencial
BEGIN
SELECT
    NVL(MAX(CD_REGISTRO_SECUENCIAL), 0) + 1 INTO V_SEC
FROM
    T_DIAGNOSTICO_DE_INFECCION
WHERE
    CD_PRESCRIPCION = V_CD_PRESCRIPCION;

EXCEPTION WHEN OTHERS THEN V_SEC := 1;

END;

BEGIN
INSERT INTO
    T_DIAGNOSTICO_DE_INFECCION (
        CD_FORMULARIO,
        CD_ATENDIMENTO,
        FECHA_REGISTRO,
        USUARIO,
        CD_DOCUMENTO_CLINICO,
        DIAGNOSTICO_DE_INFECCION,
        CD_REGISTRO_SECUENCIAL,
        CD_PRESCRIPCION
    )
VALUES
    (
        V_CD_FORMULARIO,
        V_CD_ATENDIMIENTO,
        V_FECHA_REGISTRO,
        V_USUARIO,
        V_CD_DOCUMENTO_CLINICO,
        V_DIAGNOSTICO_DE_INFECCION,
        V_SEC,
        V_CD_PRESCRIPCION
    );

EXCEPTION WHEN OTHERS THEN NULL;

END;

ELSE
BEGIN
UPDATE T_DIAGNOSTICO_DE_INFECCION
SET
    CD_FORMULARIO = V_CD_FORMULARIO,
    FECHA_REGISTRO = V_FECHA_REGISTRO,
    USUARIO = V_USUARIO,
    CD_DOCUMENTO_CLINICO = V_CD_DOCUMENTO_CLINICO,
    DIAGNOSTICO_DE_INFECCION = V_DIAGNOSTICO_DE_INFECCION
WHERE
    CD_REGISTRO_SECUENCIAL = V_CD_REGISTRO_SECUENCIAL
    --AND CD_ATENDIMENTO = V_CD_ATENDIMIENTO
    AND CD_PRESCRIPCION = V_CD_PRESCRIPCION;

EXCEPTION WHEN OTHERS THEN NULL;

END;

END IF;

COMMIT;

END PRC_INSERTA_T_DIAG_INFECCION;