CREATE
OR REPLACE PROCEDURE prc_elimina_sonda_ali (
    V_CD_ATENDIMENTO NUMBER,
    V_CD_REGISTRO_SECUENCIAL NUMBER
) IS
BEGIN
DELETE FROM T_SONDAS_ALIMENTACION
WHERE
    CD_ATENDIMENTO = V_CD_ATENDIMENTO
    AND CD_REGISTRO_SECUENCIAL = V_CD_REGISTRO_SECUENCIAL;

COMMIT;

EXCEPTION WHEN OTHERS THEN NULL;

END prc_elimina_sonda_ali;

/