SELECT
    T_LINEAS_INTRAVENOSAS.CD_REGISTRO_SECUENCIAL AS "ID",
    T_LINEAS_INTRAVENOSAS.FECHA_INICIO           AS "Fecha Inicio",
    T_LINEAS_INTRAVENOSAS.TIPO                   AS "Tipo",
    T_LINEAS_INTRAVENOSAS.LOCALIZACION           AS "Localización",
    T_LINEAS_INTRAVENOSAS.CUIDADOS               AS "Cuidados",
    T_LINEAS_INTRAVENOSAS.FECHA_CURACION
FROM
    T_LINEAS_INTRAVENOSAS