CREATE OR REPLACE PROCEDURE INSERTAR_VALORES_GAC(
    V_CANTIDAD NUMBER,
    V_DESCRIPCION VARCHAR2
) IS
BEGIN
    INSERT INTO GAC (
        CANTIDAD,
        DESCRIPCION
    ) VALUES (
        V_CANTIDAD,
        V_DESCRIPCION
    );
    --COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        NULL;
END INSERTAR_VALORES_GAC;