SELECT
    E.NM_PRESTADOR || ' - '|| D.DS_ESPECIALID MEDICO_INTERCONSULTADO
FROM
    PAR_MED B,
    ESPECIALID D,
    PRESTADOR E,
    PRESTADOR F
WHERE
    B.CD_ATENDIMENTO =98321
    AND B.CD_ESPECIALID = D.CD_ESPECIALID
    AND B.CD_PRESTADOR_REQUISITADO = E.CD_PRESTADOR
    AND B.CD_PRESTADOR = F.CD_PRESTADOR --and b.cd_par_med='&<485899:DATOS_DOCTOR593___V20>'
    SELECT
        E.NM_PRESTADOR || ' - '|| D.DS_ESPECIALID MEDICO_INTERCONSULTADO
    FROM
        PAR_MED B,
        ESPECIALID D,
        PRESTADOR E,
        PRESTADOR F
    WHERE
        B.CD_ATENDIMENTO ='&<PAR_CD_ATENDIMENTO>'
        AND B.CD_ESPECIALID = D.CD_ESPECIALID
        AND B.CD_PRESTADOR_REQUISITADO = E.CD_PRESTADOR
        AND B.CD_PRESTADOR = F.CD_PRESTADOR
        AND B.CD_PAR_MED='&<485899:DATOS_DOCTOR593___V20>'