SELECT
    P.DS_PRIMEIRO_SOBRENOME
    ||' '
    || P.DS_SEGUNDO_SOBRENOME
    ||' '
    ||P.DS_PRIMEIRO_NOME
    ||' '
    ||P.DS_SEGUNDO_NOME NOMBRE,
    FN_IDADE(DT_NASCIMENTO,'a "a", m "m", d "d"') EDAD
FROM
    PACIENTE P,
    ATENDIME A
WHERE
    P.CD_PACIENTE=A.CD_PACIENTE
    AND A.CD_ATENDIMENTO=110358
    and A.CD_PACIENTE=P.CD_PACIENTE