SELECT
    PLANTILLA.ID,
    PLANTILLA.ID
    || ' - '
    || PLANTILLA.DS_PLANTILLA
    || ' - '
    || USUARIOS.CD_USUARIO
    || ' - '
    || TO_CHAR(PLANTILLA.FECHA_CREACION, 'DD/MM/YYYY hh24:mi') INFORMACION,
    'N'
FROM
    EDITOR_CUSTOM.T_PLANTILLA_OPERATORIO PLANTILLA
    INNER JOIN PRESTADOR
    ON PRESTADOR.CD_PRESTADOR = PLANTILLA.CD_CIRUJANO
    INNER JOIN USUARIOS
    ON PRESTADOR.CD_PRESTADOR = USUARIOS.CD_PRESTADOR
WHERE
    PRESTADOR.CD_PRESTADOR = (
        SELECT
            USUARIOS.CD_PRESTADOR
        FROM
            USUARIOS
        WHERE
            CD_USUARIO = 'DBAMV'
    )
ORDER BY
    PLANTILLA.ID