CREATE OR REPLACE PROCEDURE PRC_INSERTA_T_PLANT_OPERATORIO (
  V_ID NUMBER,
  V_DS_PLANTILLA VARCHAR2,
  V_CD_CIRUJANO NUMBER,
  V_CD_CREA NUMBER,
  V_CD_ACTUALIZA NUMBER,
  V_DIAGNOSTICO_PRE_OPERATORIO VARCHAR2,
  V_DIAGNOSTICO_POST_OPERATORIO VARCHAR2,
  V_OPERACION_PROYECTADA VARCHAR2,
  V_OPERACION_REALIZADA VARCHAR2,
  V_PROGRAMACION VARCHAR2,
  V_DIERESIS VARCHAR2,
  V_EXPOSICION VARCHAR2,
  V_HALLAZGOS VARCHAR2,
  V_PROCEDIMIENTO_QUIRURGICO CLOB,
  V_COMPLICACIONES VARCHAR2,
  V_SANGRADO VARCHAR2,
  V_CULTIVO VARCHAR2,
  V_PATOLOGIA VARCHAR2,
  V_ORTESIS_PROTESIS VARCHAR2,
  V_DRENAJES VARCHAR2,
  V_OTROS VARCHAR2,
  V_DESTINO VARCHAR2,
  V_POSICION VARCHAR2,
  V_TIPO_CIRUGIA VARCHAR2,
  V_USO_HEMODERIVADOS VARCHAR2,
  V_OBSERVACION_HEMODERIVADOS VARCHAR2,
  V_ANTIBIOTICO_PROFILACTICO VARCHAR2,
  V_TIEMPO_PROFILAXIS VARCHAR2,
  V_PROFILAXIS VARCHAR2,
  V_OTRO_ANTB_PROF VARCHAR2,
  V_DOSIS VARCHAR2,
  V_OTRA_DOSIS_PRF VARCHAR2,
  V_REPETIR_DOSIS VARCHAR2,
  V_TRATAMIENTO VARCHAR2,
  V_OBSERVACION_TRATAMIENTO VARCHAR2
) IS
BEGIN
  IF V_ID IS NULL THEN
    BEGIN
      INSERT INTO T_PLANTILLA_OPERATORIO (
        ds_plantilla,
        cd_cirujano,
        cd_crea,
        fecha_creacion,
        cd_actualiza,
        diagnostico_pre_operatorio,
        diagnostico_post_operatorio,
        operacion_proyectada,
        operacion_realizada,
        programacion,
        dieresis,
        exposicion,
        hallazgos,
        procedimiento_quirurgico,
        complicaciones,
        sangrado,
        cultivo,
        patologia,
        ortesis_protesis,
        drenajes,
        otros,
        destino,
        posicion,
        tipo_cirugia,
        uso_hemoderivados,
        observacion_hemoderivados,
        antibiotico_profilactico,
        tiempo_profilaxis,
        profilaxis,
        otro_antb_prof,
        dosis,
        otra_dosis_prf,
        repetir_dosis,
        tratamiento,
        observacion_tratamiento
      ) VALUES (
        V_DS_PLANTILLA,
        V_CD_CIRUJANO,
        V_CD_CREA,
        sysdate,
        V_CD_ACTUALIZA,
        V_DIAGNOSTICO_PRE_OPERATORIO,
        V_DIAGNOSTICO_POST_OPERATORIO,
        V_OPERACION_PROYECTADA,
        V_OPERACION_REALIZADA,
        V_PROGRAMACION,
        V_DIERESIS,
        V_EXPOSICION,
        V_HALLAZGOS,
        V_PROCEDIMIENTO_QUIRURGICO,
        V_COMPLICACIONES,
        V_SANGRADO,
        V_CULTIVO,
        V_PATOLOGIA,
        V_ORTESIS_PROTESIS,
        V_DRENAJES,
        V_OTROS,
        V_DESTINO,
        V_POSICION,
        V_TIPO_CIRUGIA,
        V_USO_HEMODERIVADOS,
        V_OBSERVACION_HEMODERIVADOS,
        V_ANTIBIOTICO_PROFILACTICO,
        V_TIEMPO_PROFILAXIS,
        V_PROFILAXIS,
        V_OTRO_ANTB_PROF,
        V_DOSIS,
        V_OTRA_DOSIS_PRF,
        V_REPETIR_DOSIS,
        V_TRATAMIENTO,
        V_OBSERVACION_TRATAMIENTO
      );
    EXCEPTION
      WHEN OTHERS THEN
        NULL;
    END;
  ELSE
    BEGIN
      UPDATE T_PLANTILLA_OPERATORIO
      SET
        ds_plantilla = V_DS_PLANTILLA,
        cd_actualiza = V_CD_ACTUALIZA,
        fecha_actualizacion = SYSDATE,
        diagnostico_pre_operatorio = V_DIAGNOSTICO_PRE_OPERATORIO,
        diagnostico_post_operatorio = V_DIAGNOSTICO_POST_OPERATORIO,
        operacion_proyectada = V_OPERACION_PROYECTADA,
        operacion_realizada = V_OPERACION_REALIZADA,
        programacion = V_PROGRAMACION,
        dieresis = V_DIERESIS,
        exposicion = V_EXPOSICION,
        hallazgos = V_HALLAZGOS,
        procedimiento_quirurgico = V_PROCEDIMIENTO_QUIRURGICO,
        complicaciones = V_COMPLICACIONES,
        sangrado = V_SANGRADO,
        cultivo = V_CULTIVO,
        patologia = V_PATOLOGIA,
        ortesis_protesis = V_ORTESIS_PROTESIS,
        drenajes = V_DRENAJES,
        otros = V_OTROS,
        destino = V_DESTINO,
        posicion = V_POSICION,
        tipo_cirugia = V_TIPO_CIRUGIA,
        uso_hemoderivados = V_USO_HEMODERIVADOS,
        observacion_hemoderivados = V_OBSERVACION_HEMODERIVADOS,
        antibiotico_profilactico = V_ANTIBIOTICO_PROFILACTICO,
        tiempo_profilaxis = V_TIEMPO_PROFILAXIS,
        profilaxis = V_PROFILAXIS,
        otro_antb_prof = V_OTRO_ANTB_PROF,
        dosis = V_DOSIS,
        otra_dosis_prf = V_OTRA_DOSIS_PRF,
        repetir_dosis = V_REPETIR_DOSIS,
        tratamiento = V_TRATAMIENTO,
        observacion_tratamiento = V_OBSERVACION_TRATAMIENTO
      WHERE
        id = V_ID;
    EXCEPTION
      WHEN OTHERS THEN
        NULL;
    END;
  END IF;
  COMMIT;
END PRC_INSERTA_T_PLANT_OPERATORIO;
