SELECT
    DECODE(A.ESTABLE, 'true', 'X', null) ESTABLE, -- 49
    DECODE(A.INESTABLE, 'true', 'X', null) INESTABLE, -- 50
    DECODE(A.Fallecido, 'true', 'X', null) FALLECIDO, -- 51
    A.DESCRIPCION_OTRO_MOTIVO DESCRIPCION_OTRO_MOTIVO, -- 52
    DECODE(A.TIPO_MOTIVO_ATENCION, 'TRAUMA', 'true', 'false') TRAUMA_X, -- 53
    DECODE(
        A.TIPO_MOTIVO_ATENCION,
        'CAUSA CLÍNICA',
        'true',
        'false'
    ) CAUSA_CLINICA_X, -- 54
    DECODE(
        A.TIPO_MOTIVO_ATENCION,
        'CAUSA G. OBSTÉTRICA',
        'true',
        'false'
    ) CAUSA_OBSTETRICA_X, --55
    DECODE(
        A.TIPO_MOTIVO_ATENCION,
        'CAUSA QUIRÚRGICA',
        'true',
        'false'
    ) CAUSA_QUIRURGICA_X, --56
    A.DETALLE_ENFERMEDAD_ACTUAL ENFERMEDAD_ACTUAL, -- 100
    -- DATOS GINECOLOGICOS
    CASE
        WHEN A.GESTAS IS NULL
        AND A.PARTOS IS NULL
        AND A.ABORTOS IS NULL
        AND A.CESAREAS IS NULL
        AND A.FUM IS NULL
        AND A.SEMANAS_GESTACION IS NULL
        AND A.MOVIMIENTO IS NULL
        AND A.FRECUENCIA_FETAL IS NULL
        AND A.MEMBRANAS_ROTAS IS NULL
        AND A.TIEMPO IS NULL
        AND A.ALTURA_UTERINA IS NULL
        AND A.PRESENTACION IS NULL
        AND A.DILATACION IS NULL
        AND A.BORRAMIENTO IS NULL
        AND A.PLANO IS NULL
        AND A.pelvis_viable IS NULL
        AND A.SANGRADO_VAGINAL IS NULL
        AND A.CONTRACCIONES IS NULL
        AND A.score_mama IS NULL
        AND A.OBSERVACIONES_OTRO_EXAMEN IS NULL THEN 'X'
        ELSE NULL
    END NO_APLICA, -- 133
    A.GESTAS, -- 134
    A.PARTOS, -- 135
    A.ABORTOS, -- 136
    A.CESAREAS, -- 137
    A.FUM, -- 138
    A.SEMANAS_GESTACION, -- 139
    A.MOVIMIENTO, -- 140
    A.FRECUENCIA_FETAL, -- 141
    A.MEMBRANAS_ROTAS, -- 142
    A.TIEMPO, -- 143
    A.ALTURA_UTERINA, -- 144
    A.PRESENTACION, -- 145
    A.DILATACION, -- 146
    A.BORRAMIENTO, -- 147
    A.PLANO, -- 148,
    A.pelvis_viable, -- 149
    A.SANGRADO_VAGINAL, -- 150
    A.CONTRACCIONES, -- 151
    A.score_mama, -- 152
    A.OBSERVACIONES_OTRO_EXAMEN OBSERVACIONES_OTRO_EXAMEN, -- 153 
    -- Fecha y hora actual
    TO_CHAR(SYSDATE, 'DD/MM/YYYY HH24:MI') FECHA_HORA_ACTUAL, -- 175  
    U.NM_USUARIO USUARIO_CREA, -- 176 
    U.CD_IDENTIFICADOR_PESSOA CODIGO_CREA, -- 177 
    A.FUENTE_INFORMACION, -- Es el campo 45
    A.FECHA_EVENTO FECHA_EVENTO, -- Es el campo 58.
    A.LUGAR_EVENTO LUGAR_EVENTO, -- Es el campo 59.
    A.DIRECCION_EVENTO DIRECCION_EVENTO, --  Es el campo 60
    -- G. Constantes vitales y antropometría
    (
        select
            case
                when count(*) = 0 then 'X'
                else null
            end
        from
            dbamv.coleta_sinal_vital
        where
            cd_atendimento = VATENDIMENTO
    ) SIN_CONSTANTES_VITALES, --101
    FUN_SIGNOS_VITALES (A.CD_ATENDIMENTO, 4) || ' / ' || FUN_SIGNOS_VITALES (A.CD_ATENDIMENTO, 5) PRESION_ARTERIAL_CONCATENADA, -- 102
    FUN_SIGNOS_VITALES (A.CD_ATENDIMENTO, 2) FRECUENCIA_CARDIACA, -- 103
    FUN_SIGNOS_VITALES (A.CD_ATENDIMENTO, 3) FRECUENCIA_RESPIRATORIA, -- 104
    -- 105 falta
    fun_signos_vitales_u_t (A.CD_ATENDIMENTO, 'CÉFALICO') PERIMETRO_CEFALICO, -- 106 
    FUN_SIGNOS_VITALES_U (A.CD_ATENDIMENTO, 8) PESO, -- 107
    FUN_SIGNOS_VITALES_U (A.CD_ATENDIMENTO, 9) TALLA, -- 108
    FUN_SIGNOS_VITALES (A.CD_ATENDIMENTO, 17) GLICEMIA_CAPILAR, -- 109 
    FUN_SIGNOS_VITALES_GLASGOW (A.CD_ATENDIMENTO, 'OCULAR') OCULAR, -- 110
    FUN_SIGNOS_VITALES_GLASGOW (A.CD_ATENDIMENTO, 'VERBAL') VERBAL, -- 111
    FUN_SIGNOS_VITALES_GLASGOW (A.CD_ATENDIMENTO, 'MOTORA') MOTORA, -- 112
    FUN_SIGNOS_VITALES (A.CD_ATENDIMENTO, 42) REACCION_DERECHA, -- 113
    FUN_SIGNOS_VITALES (A.CD_ATENDIMENTO, 43) REACCION_IZQUIERDA, -- 114
    FUN_SIGNOS_VITALES (A.CD_ATENDIMENTO, 41) LLENADO_CAPILAR -- 115
    /* INTO 
    V_CAMPO49,
    V_CAMPO50,
    V_CAMPO51,
    V_CAMPO52,
    V_CAMPO53,
    V_CAMPO54,
    V_CAMPO55,
    V_CAMPO56,
    V_CAMPO57,
    V_CAMPO100,
    V_CAMPO133,
    V_CAMPO134,
    V_CAMPO135,
    V_CAMPO136,
    V_CAMPO137,
    V_CAMPO138,
    V_CAMPO139,
    V_CAMPO140,
    V_CAMPO141,
    V_CAMPO142,
    V_CAMPO143,
    V_CAMPO144,
    V_CAMPO145,
    V_CAMPO146,
    V_CAMPO147,
    V_CAMPO148,
    V_CAMPO149,
    V_CAMPO150,
    V_CAMPO151,
    V_CAMPO152,
    V_CAMPO153,
    V_CAMPO175,
    V_CAMPO45,
    V_CAMPO158,
    V_CAMPO59,
    V_CAMPO60,
    V_CAMPO101,
    V_CAMPO102,
    V_CAMPO103,
    V_CAMPO104,
    -- V_CAMPO105, falta 
    V_CAMPO106,
    V_CAMPO107,
    V_CAMPO108,
    V_CAMPO109,
    V_CAMPO110,
    V_CAMPO111,
    V_CAMPO112,
    V_CAMPO113,
    V_CAMPO114,
    V_CAMPO115
     */
FROM
    T_EMERGENCIA A,
    USUARIOS U
WHERE
    A.CD_ATENDIMENTO = VATENDIMENTO --79919--96372--96370--VATENDIMENTO
    AND TRIM(A.USUARIO) = U.CD_USUARIO
    AND A.CD_ULTIMO_REGISTRO IN (
        SELECT
            MAX(B.CD_ULTIMO_REGISTRO)
        FROM
            T_EMERGENCIA B
        WHERE
            B.CD_ATENDIMENTO = VATENDIMENTO --79919--654--96372--96370--VATENDIMENTO
    );