SELECT
    DECODE(A.ESTABLE, 'true', 'X', null) ESTABLE, -- 49
    DECODE(A.INESTABLE, 'true', 'X', null) INESTABLE, -- 50
    DECODE(A.Fallecido, 'true', 'X', null) FALLECIDO, -- 51
    A.DESCRIPCION_OTRO_MOTIVO DESCRIPCION_OTRO_MOTIVO, -- 52
    DECODE(A.TIPO_MOTIVO_ATENCION, 'TRAUMA', 'true', 'false') TRAUMA_X, -- 53
    DECODE(
        A.TIPO_MOTIVO_ATENCION,
        'CAUSA CLÍNICA',
        'true',
        'false'
    ) CAUSA_CLINICA_X, -- 54
    DECODE(
        A.TIPO_MOTIVO_ATENCION,
        'CAUSA G. OBSTÉTRICA',
        'true',
        'false'
    ) CAUSA_OBSTETRICA_X, --55
    DECODE(
        A.TIPO_MOTIVO_ATENCION,
        'CAUSA QUIRÚRGICA',
        'true',
        'false'
    ) CAUSA_QUIRURGICA_X, --56
    A.DETALLE_ENFERMEDAD_ACTUAL ENFERMEDAD_ACTUAL, -- 100
    -- DATOS GINECOLOGICOS
    CASE
        WHEN
            A.GESTAS IS NULL AND
            A.PARTOS IS NULL AND
            A.ABORTOS IS NULL AND
            A.CESAREAS IS NULL AND
            A.FUM IS NULL AND
            A.SEMANAS_GESTACION IS NULL AND
            A.MOVIMIENTO IS NULL AND
            A.FRECUENCIA_FETAL IS NULL AND
            A.MEMBRANAS_ROTAS IS NULL AND
            A.TIEMPO IS NULL AND
            A.ALTURA_UTERINA IS NULL AND
            A.PRESENTACION IS NULL AND
            A.DILATACION IS NULL AND
            A.BORRAMIENTO IS NULL AND
            A.PLANO IS NULL AND
            A.pelvis_viable IS NULL AND
            A.SANGRADO_VAGINAL IS NULL AND
            A.CONTRACCIONES IS NULL AND
            A.score_mama IS NULL AND
            A.OBSERVACIONES_OTRO_EXAMEN IS NULL
        THEN 'X'
        ELSE NULL 
    END NO_APLICA, -- 133
    A.GESTAS, -- 134
    A.PARTOS, -- 135
    A.ABORTOS, -- 136
    A.CESAREAS, -- 137
    A.FUM, -- 138
    A.SEMANAS_GESTACION, -- 139
    A.MOVIMIENTO, -- 140
    A.FRECUENCIA_FETAL, -- 141
    A.MEMBRANAS_ROTAS, -- 142
    A.TIEMPO, -- 143
    A.ALTURA_UTERINA, -- 144
    A.PRESENTACION, -- 145
    A.DILATACION, -- 146
    A.BORRAMIENTO, -- 147
    A.PLANO, -- 148,
    A.pelvis_viable, -- 149
    A.SANGRADO_VAGINAL, -- 150
    A.CONTRACCIONES, -- 151
    A.score_mama, -- 152
    A.OBSERVACIONES_OTRO_EXAMEN OBSERVACIONES_OTRO_EXAMEN, -- 153 
    -- Fecha y hora actual
    TO_CHAR(SYSDATE, 'DD/MM/YYYY HH24:MI') FECHA_HORA_ACTUAL, -- 175  
    U.NM_USUARIO USUARIO_CREA,-- 176 
    U.CD_IDENTIFICADOR_PESSOA CODIGO_CREA,-- 177 
    A.FUENTE_INFORMACION, -- Es el campo 45
    A.FECHA_EVENTO FECHA_EVENTO, -- Es el campo 58.
    A.LUGAR_EVENTO LUGAR_EVENTO, -- Es el campo 59.
    A.DIRECCION_EVENTO DIRECCION_EVENTO --  Es el campo 60
    /* A.PELVIS_UTIL,
    A.SANGRADO_VAGINAL,
    A.CONTRACCIONES,
    A.MONITOREO_GINECOLOGICO,
    A.FECHA_EVENTO,
    A.LUGAR_EVENTO,
    A.DIRECCION_EVENTO,
    DECODE(NVL(A.ALCOCHECK, 'NO'), 'NO', 'false', 'true') ALCOCHECK,
    DECODE(A.VIA_AEREA, 'LIBRE', 'true', 'false') VIA_AREA_LIBRE,
    DECODE(A.VIA_AEREA, 'OBSTRUÍDA', 'true', 'false') VIA_AREA_OBSTRUIDA,
    DECODE(A.CONDICION, 'ESTABLE', 'true', 'false') CONDICION_ESTABLE,
    DECODE(A.CONDICION, 'INESTABLE', 'true', 'false') CONDICION_INESTABLE,
    A.DETALLE_ENFERMEDAD_ACTUAL ENFERMEDAD_ACTUAL,
    -- SIGNOS VITALES
    FUN_SIGNOS_VITALES (A.CD_ATENDIMENTO, 4) PRESION_ARTERIAL_1,
    FUN_SIGNOS_VITALES (A.CD_ATENDIMENTO, 5) PRESION_ARTERIAL_2,
    FUN_SIGNOS_VITALES (A.CD_ATENDIMENTO, 2) FRECUENCIA_CARDIACA,
    FUN_SIGNOS_VITALES (A.CD_ATENDIMENTO, 3) FRECUENCIA_RESPIRATORIA,
    FUN_SIGNOS_VITALES_TEMPERATURA (A.CD_ATENDIMENTO, 8) TEMPERATURA_BUCAL,
    FUN_SIGNOS_VITALES_TEMPERATURA (A.CD_ATENDIMENTO, 7) TEMPERATURA_AXILAR,
    FUN_SIGNOS_VITALES_U (A.CD_ATENDIMENTO, 8) PESO,
    FUN_SIGNOS_VITALES_U (A.CD_ATENDIMENTO, 9) TALLA,
    FUN_SIGNOS_VITALES_IMC (A.CD_ATENDIMENTO) IMC,
    FUN_SIGNOS_VITALES_GLASGOW (A.CD_ATENDIMENTO, 'OCULAR') OCULAR,
    FUN_SIGNOS_VITALES_GLASGOW (A.CD_ATENDIMENTO, 'VERBAL') VERBAL,
    FUN_SIGNOS_VITALES_GLASGOW (A.CD_ATENDIMENTO, 'MOTORA') MOTORA,
    FUN_SIGNOS_VITALES_GLASGOW_T_U (A.CD_ATENDIMENTO) TOTAL_GLASGOW,
    FUN_SIGNOS_VITALES (A.CD_ATENDIMENTO, 42) REACCION_DERECHA,
    FUN_SIGNOS_VITALES (A.CD_ATENDIMENTO, 43) REACCION_IZQUIERDA,
    FUN_SIGNOS_VITALES (A.CD_ATENDIMENTO, 41) LLENADO_CAPILAR,
    FUN_SIGNOS_VITALES (A.CD_ATENDIMENTO, 7) SATURACION_OXIGENO,
    -- HERIDAS
    DECODE(A.LOCALIZACION_1, 0, NULL, A.LOCALIZACION_1) LOCALIZACION_1,
    DECODE(A.LOCALIZACION_2, 0, NULL, A.LOCALIZACION_2) LOCALIZACION_2,
    DECODE(A.LOCALIZACION_3, 0, NULL, A.LOCALIZACION_3) LOCALIZACION_3,
    DECODE(A.LOCALIZACION_4, 0, NULL, A.LOCALIZACION_4) LOCALIZACION_4,
    DECODE(A.LOCALIZACION_5, 0, NULL, A.LOCALIZACION_5) LOCALIZACION_5,
    DECODE(A.LOCALIZACION_6, 0, NULL, A.LOCALIZACION_6) LOCALIZACION_6,
    DECODE(A.LOCALIZACION_7, 0, NULL, A.LOCALIZACION_7) LOCALIZACION_7,
    DECODE(A.LOCALIZACION_8, 0, NULL, A.LOCALIZACION_8) LOCALIZACION_8,
    DECODE(A.LOCALIZACION_9, 0, NULL, A.LOCALIZACION_9) LOCALIZACION_9,
    DECODE(A.LOCALIZACION_10, 0, NULL, A.LOCALIZACION_10) LOCALIZACION_10,
    DECODE(A.LOCALIZACION_11, 0, NULL, A.LOCALIZACION_11) LOCALIZACION_11,
    DECODE(A.LOCALIZACION_12, 0, NULL, A.LOCALIZACION_12) LOCALIZACION_12,
    DECODE(A.LOCALIZACION_13, 0, NULL, A.LOCALIZACION_13) LOCALIZACION_13,
    DECODE(A.LOCALIZACION_14, 0, NULL, A.LOCALIZACION_14) LOCALIZACION_14,
    DECODE(A.LOCALIZACION_15, 0, NULL, A.LOCALIZACION_15) LOCALIZACION_15,
    A.LOCALIZACION_OTRO,
    -- DATOS GINECOLOGICOS
    A.GESTAS,
    A.PARTOS,
    A.ABORTOS,
    A.CESAREAS,
    A.FUM,
    A.SEMANAS_GESTACION,
    A.MOVIMIENTO,
    A.FRECUENCIA_FETAL,
    A.MEMBRANAS_ROTAS,
    A.TIEMPO,
    A.ALTURA_UTERINA,
    A.PRESENTACION,
    A.DILATACION,
    A.BORRAMIENTO,
    A.PLANO,
    A.PELVIS_UTIL,
    A.SANGRADO_VAGINAL,
    A.CONTRACCIONES,
    A.MONITOREO_GINECOLOGICO,
    -- OTROS EXAMENES
    OBSERVACIONES_OTRO_EXAMEN,
    DECODE(
        TRIM(A.CONSENTIMIENTO_VERBAL),
        'SI',
        'true',
        'false'
    ) CONSENTIMIENTO_VERBAL,
    -- DIAGNOSTICOS
    FUN_DIAGNOSTICOS_INGRESO_008 (A.CD_ATENDIMENTO) DIAGNOSTICO_INGRESO,
    FUN_DIAGNOSTICOS_EGRESO_008 (A.CD_ATENDIMENTO) DIAGNOSTICO_EGRESO,
    -- PLANES DE EGRESO
    'INDICACIONES' || CHR(10) || '---------------------' || CHR(10) || PLANES_TRATAMIENTO PLAN_TRATAMIENTO_1,
    FUN_DETALLE_MEDICACION_008 (A.CD_ATENDIMENTO) PLAN_TRATAMIENTO_2,
    -- FINAL USUARIO
    U.NM_USUARIO USUARIO_CREA,
    U.CD_IDENTIFICADOR_PESSOA CODIGO_CREA,
    A.TELEFONO_FUENTE  */
    
    /* INTO 
    V_CAMPO49,
    V_CAMPO50,
    V_CAMPO51,
    V_CAMPO52,
    V_CAMPO53,
    V_CAMPO54,
    V_CAMPO55,
    V_CAMPO56,
    V_CAMPO57,
    V_CAMPO100,
    V_CAMPO134,
    V_CAMPO135,
    V_CAMPO136,
    V_CAMPO137,
    V_CAMPO138,
    V_CAMPO139,
    V_CAMPO140,
    V_CAMPO141,
    V_CAMPO142,
    V_CAMPO143,
    V_CAMPO144,
    V_CAMPO145,
    V_CAMPO146,
    V_CAMPO147,
    V_CAMPO148,
    V_CAMPO149,
    V_CAMPO150,
    V_CAMPO151,
    V_CAMPO152,
    V_CAMPO153,
    V_CAMPO175
    V_CAMPO176,
    V_CAMPO177,
    V_CAMPO45,
    V_CAMPO58,
    V_CAMPO59,
    V_CAMPO60
     */
FROM
    T_EMERGENCIA A,
    USUARIOS U
WHERE
    A.CD_ATENDIMENTO = 654--79919--96372--96370--VATENDIMENTO
    AND TRIM(A.USUARIO) = U.CD_USUARIO
    AND A.CD_ULTIMO_REGISTRO IN (
        SELECT
            MAX(B.CD_ULTIMO_REGISTRO)
        FROM
            T_EMERGENCIA B
        WHERE
            B.CD_ATENDIMENTO = 654--79919--654--96372--96370--VATENDIMENTO
    );