CREATE OR REPLACE PROCEDURE PRC_ACTUALIZA_ANTIBIOTICOS (
    V_CD_SECUENCIAL NUMBER,
    V_ESTADO NVARCHAR2,
    V_MOTIVO NVARCHAR2,
    V_VALIDADO_POR NVARCHAR2
) IS
BEGIN
BEGIN
UPDATE T_AUTORIZACION_ANTIBIOTICOS
SET
    ESTADO = V_ESTADO,
    MOTIVO = V_MOTIVO,
    VALIDADO_POR = V_VALIDADO_POR
WHERE
    CD_SECUENCIAL = V_CD_SECUENCIAL;

EXCEPTION WHEN OTHERS THEN NULL;

END;

COMMIT;

END PRC_ACTUALIZA_ANTIBIOTICOS;