select * from t_lineas_intravenosas

/*
SELECT
    T_LINEAS_INTRAVENOSAS.CD_REGISTRO_SECUENCIAL AS "ID",
    T_LINEAS_INTRAVENOSAS.FECHA_INICIO AS "Fecha Inicio",
    T_LINEAS_INTRAVENOSAS.TIPO AS "Tipo",
    T_LINEAS_INTRAVENOSAS.LOCALIZACION AS "Localización",
    T_LINEAS_INTRAVENOSAS.CUIDADOS AS "Cuidados",
    T_LINEAS_INTRAVENOSAS.FECHA_CURACION AS "Fecha de Curación"
FROM
    EDITOR_CUSTOM.T_LINEAS_INTRAVENOSAS
WHERE 

*/

SELECT
    CD_REGISTRO_SECUENCIAL,
    FECHA_INICIO,
    TIPO,
    LOCALIZACION,
    CUIDADOS,
    FECHA_CURACION
FROM
    EDITOR_CUSTOM.T_LINEAS_INTRAVENOSAS
WHERE 
    CD_ATENDIMENTO = 654
ORDER BY 
      FECHA_CURACION
