CREATE OR REPLACE PROCEDURE PRC_ELIMINA_LINEA_INTRA(
    V_CD_ATENDIMENTO NUMBER,
    V_CD_REGISTRO_SECUENCIAL NUMBER
) IS
BEGIN
    DELETE FROM T_LINEAS_INTRAVENOSAS
    WHERE
        CD_ATENDIMENTO=V_CD_ATENDIMENTO
        AND CD_REGISTRO_SECUENCIAL =V_CD_REGISTRO_SECUENCIAL;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        NULL;
END PRC_ELIMINA_LINEA_INTRA;