CREATE OR REPLACE FUNCTION FUN_OBTENER_MEDICO_PRIORIDAD(
    P_CD_PRE_MED IN NUMBER
) RETURN VARCHAR2 IS
    V_NM_PRESTADOR VARCHAR2(255);
BEGIN
    SELECT
        PRESTADOR.NM_PRESTADOR INTO V_NM_PRESTADOR
    FROM
        PRE_MED
        INNER JOIN PRESTADOR
        ON PRESTADOR.CD_PRESTADOR = PRE_MED.CD_PRESTADOR
        INNER JOIN T_SOLICITUD_HEMO
        ON T_SOLICITUD_HEMO.CD_PRE_MED = PRE_MED.CD_PRE_MED
    WHERE
        T_SOLICITUD_HEMO.CD_PRE_MED = P_CD_PRE_MED
        AND T_SOLICITUD_HEMO.PRIORIDAD IN ('URGENCIA (15 min)', 'EMERGENCIA (5 min)');
    RETURN V_NM_PRESTADOR;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN NULL;
END FUN_OBTENER_MEDICO_PRIORIDAD;